---
title: "HospitalRankings"
author: "Michael Zelenetz, Xiojing Yang"
date: "April 20, 2016"
output: html_document
---

Load data from local file:
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
#cost sets
paymentandvalue <- read.csv("https://raw.githubusercontent.com/anniey/Hospital-Ranking-CS107/master/Raw%20Data/Payment_and_value_of_care_-_Hospital.csv") #national
inpatientcost <- read.csv("https://raw.githubusercontent.com/anniey/Hospital-Ranking-CS107/master/Raw%20Data/Hospital_Inpatient_Cost_Transparency__Beginning_2009.csv") #NYS

#risk of badness sets
PCIbyhospital <- read.csv("https://raw.githubusercontent.com/anniey/Hospital-Ranking-CS107/master/Raw%20Data/Cardiac_Surgery_and_Percutaneous_Coronary_Interventions_by_Hospital___Beginning_2008.csv") #NYS
hospitalinfection <- read.csv("https://raw.githubusercontent.com/anniey/Hospital-Ranking-CS107/master/Raw%20Data/Hospital-Acquired_Infections__Beginning_2008.csv") #NYS
complicationshospital <- read.csv("https://raw.githubusercontent.com/anniey/Hospital-Ranking-CS107/master/Raw%20Data/Readmissions_Complications_and_Deaths_-_Hospital.csv") #national

#service
hcahps <- read.csv("https://raw.githubusercontent.com/anniey/Hospital-Ranking-CS107/master/Raw%20Data/hcahps.csv") #NYS
timely <- read.csv("https://raw.githubusercontent.com/anniey/Hospital-Ranking-CS107/master/Raw%20Data/Timely_and_Effective_Care_-_Hospital.csv") #national

#readmisisons
readmission <- read.csv("https://raw.githubusercontent.com/anniey/Hospital-Ranking-CS107/master/Raw%20Data/Hospital_Readmissions_Reduction_Program.csv") #national 
```

##Wrangling
Limit Data Sets to NYS only:
```{r}
paymentandvalue <- paymentandvalue %>% filter(State=="NY")
complicationshospital <- complicationshospital %>% filter(State=="NY")
hcahps <- hcahps %>% filter(State=="NY")
timely <- timely %>% filter(State=="NY")
readmission <- readmission %>% filter(State=="NY")
```

Join data sets by hospital name
```{r}

#first, join the datasets with providerIDs
providerID_data <- complicationshospital %>%
  select(c(Provider.ID, Hospital.Name, Measure.Name, Measure.ID, Compared.to.National, Denominator, Score, Lower.Estimate, Higher.Estimate, Location))

providerID_data <- hcahps %>%
  select(c(Provider.ID, HCAHPS.Measure.ID, HCAHPS.Question, Patient.Survey.Star.Rating, HCAHPS.Answer.Percent, HCAHPS.Linear.Mean.Value)) %>%
  transform(Provider.ID = factor(Provider.ID)) %>%
  right_join(providerID_data, by = "Provider.ID")

providerID_data <- paymentandvalue %>%
  select(c(Provider.ID, Payment.measure.ID, Payment.measure.name, Payment.category, Denominator, Payment, Value.of.care.display.ID, Value.of.care.display.name, Value.of.care.category)) %>%
  right_join(providerID_data, by = "Provider.ID")

#split the coordinates from the location column. we will use it later to help ID hospitals with varying name conventions btw the provider and facility dataset
providerID_data <- providerID_data %>%
  separate(Location, into = c("Location", "Location.1"), sep = "\\(")

providerID_data$Location.1 <- gsub("\\)", "", providerID_data$Location.1)

providerID_data <- providerID_data %>%
  separate(Location.1, into = c("Location1.Long", "Location1.Lat"), sep = ",")

providerID_data <- providerID_data %>%
  transform(Location1.Long = as.numeric(Location1.Long, digits = 6))

providerID_data <- providerID_data %>%
  transform(Location1.Lat = as.numeric(Location1.Lat, digits = 6))
  
#next join all the datasets with facility ID (remove 2008 from hospitalinfection)
facilityID_data <- hospitalinfection %>%
  select(-c(Hospital.Name)) %>%
  filter(Year > 2008) %>%
  right_join(inpatientcost, by = c("Facility.Id", "Year"))

colnames(PCIbyhospital)[1] <- "Facility.Id"
colnames(PCIbyhospital)[6] <- "Year"

temp <- PCIbyhospital %>%
  select(-c(Detailed.Region, Region, Hospital.Name)) %>%
  transform(Year = as.numeric(levels(Year))[Year]) %>%
  filter(Year %in% c("2010", "2011", "2012"))

facilityID_data <- facilityID_data %>%
  filter(Year > 2009) %>%
  left_join(temp, by = c("Facility.Id", "Year"))

#remove parenthesis from location coordinates
facilityID_data$Location.1 <- gsub("\\)", "", facilityID_data$Location.1)
facilityID_data$Location.1 <- gsub("\\(", "", facilityID_data$Location.1)
  
#clean latitude and longitude
facilityID_data <- facilityID_data  %>%
  separate(Location.1, into = c("Location1.Long", "Location1.Lat"), sep = ",")

facilityID_data  <- facilityID_data  %>%
  transform(Location1.Long = as.numeric(Location1.Long, digits = 6))

facilityID_data  <- facilityID_data  %>%
  transform(Location1.Lat = as.numeric(Location1.Lat, digits = 6))

#find the hospital names that are slightly different between the datasets

HospitalNames <- facilityID_data %>%
  select(Facility.Name, Location1.Long, Location1.Lat) %>%
  as.data.frame() %>%
  unique()

colnames(HospitalNames)[1] <- c("Hospital.Name")

HospitalNames$Hospital.Name <- toupper(HospitalNames$Hospital.Name)

#find all non-matching hospital names
ProblemNames <- HospitalNames %>%
  anti_join(providerID_data , by = "Hospital.Name")

#use location to find original hospital name
ProblemNames <- providerID_data %>%
  select(Hospital.Name, Location1.Long, Location1.Lat) %>%
  right_join(HospitalNames, by = "Location1.Long")



#clean names in hcahps
levels(hcahps$Hospital.Name) <- c(levels(hcahps$Hospital.Name), "NY EYE AND EAR INFIRMARY", "HUDSON VALLEY HOSPITAL CENTER", "HEALTH ALLIANCE HOSPITAL MARY'S AVENUE CAMPUS")
hcahps$Hospital.Name[hcahps$Hospital.Name == "N Y EYE AND EAR INFIRMARY"] <- "NY EYE AND EAR INFIRMARY"
hcahps$Hospital.Name[hcahps$Hospital.Name == "NEW YORK-PRESBYTERIAN/HUDSON VALLEY HOSPITAL"] <- "HUDSON VALLEY HOSPITAL CENTER"
hcahps$Hospital.Name[hcahps$Hospital.Name == "HEALTHALLIANCE HOSPITAL MARYS AVENUE CAMPUS"] <- "HEALTH ALLIANCE HOSPITAL MARY'S AVENUE CAMPUS"


#repreat for paymentandvalue
colnames(paymentandvalue)[2] <- c("Hospital.Name")

ProblemNames <- HospitalNames %>%
  anti_join(paymentandvalue, by = "Hospital.Name")

#clean names in paymentandvalue
levels(paymentandvalue$Hospital.Name) <- c(levels(paymentandvalue$Hospital.Name), "NY EYE AND EAR INFIRMARY", "HEALTH ALLIANCE HOSPITAL MARY'S AVENUE CAMPUS",  "HUDSON VALLEY HOSPITAL CENTER")

paymentandvalue$Hospital.Name[paymentandvalue$Hospital.Name == "N Y EYE AND EAR INFIRMARY"] <- "NY EYE AND EAR INFIRMARY"
paymentandvalue$Hospital.Name[paymentandvalue$Hospital.Name == "HEALTHALLIANCE HOSPITAL MARYS AVENUE CAMPUS"] <- "HEALTH ALLIANCE HOSPITAL MARY'S AVENUE CAMPUS"
paymentandvalue$Hospital.Name[paymentandvalue$Hospital.Name == "NEW YORK-PRESBYTERIAN/HUDSON VALLEY HOSPITAL"] <- "HUDSON VALLEY HOSPITAL CENTER"


#repeat for other charts with provider
hospitalinfection$Hospital.Name <- toupper(hospitalinfection$Hospital.Name)

ProblemNames <- HospitalNames %>%
  anti_join(hospitalinfection, by = "Hospital.Name")

#keep track of names that just need some cleaning
CleaningNames <- as.data.frame("Hospitalinfection" = c("MERCY HOSPITAL OF BUFFALO, MERCY HOSPITAL", "ST JOHNS EPISCOPAL HOSPITAL SO SHORE, ST JOHN'S EPISCOPAL HOSPITAL AT SOUTH SHORE"))  

  %>%
  anti_join(inpatientcost, by = "Hospital.Name")

```

Cost set
```{r}
names(inpatientcost)[3] <- "Hospital.name"
temp<- 
cost <- left_join(inpatientcost, paymentandvalue)

```

