---
title: "Create HCAHPS Map"
output: html_document
---

This is a separate file to create the US and NYC HCAHPS Star Rating maps. The libraries choroplethr masks the summarise function of dplyr, and so this portion of the code was separated from the main file to avoid issues on that end.

```{r, warning = FALSE}
library(dplyr)
library(ggplot2)
library(choroplethr)
library(choroplethrZip) 
library(choroplethrMaps)

hcahps <- read.csv("https://raw.githubusercontent.com/anniey/Hospital-Ranking-CS107/master/Raw%20Data/hcahps.csv") #national

map_star <- read.csv("https://raw.githubusercontent.com/anniey/Hospital-Ranking-CS107/master/Raw%20Data/For%20Map%20only.csv")


colnames(map_star) <- c("county.name", "value")

map_star <- map_star %>%
  filter(value != "Not Available", value != "Not Applicable", county.name != "")

#change class and case to match the county.regions data
map_star$value <- as.numeric(as.character(map_star$value)) 
map_star$county.name <- tolower(map_star$county.name)

#map the counties to fips and find the average rating per county
data(county.regions)
map_star <- map_star %>%
  left_join(county.regions, by = "county.name") %>%
  select(c(region, value)) %>%
  dplyr::group_by(region) %>%
  dplyr::summarise(value = mean(value))

#add title and color
us_map = CountyChoropleth$new(map_star) 
us_map$title = "US HCAHPS Average Star Rating by County"
us_map$ggplot_scale = scale_fill_brewer(name="Average Star Rating", palette= "RdYlGn", drop=FALSE)

#save
ggsave(filename="USMap.png",plot=us_map$render(), path = "~/cs107/Hospital-Ranking-CS107")
  
```

NYC Star Rating Map by zip code

```{r, warning = FALSE}
#filter for just star ratings
df_star_zip <- hcahps %>%
  filter(HCAHPS.Measure.ID == "H_STAR_RATING") %>%
  select(c(ZIP.Code, Patient.Survey.Star.Rating)) 

colnames(df_star_zip) <- c("region", "value")

df_star_zip$value <- as.numeric(as.character(df_star_zip$value)) 

#calculate the mean rating
df_star_zip <- df_star_zip %>%
  na.omit() %>%
  dplyr::group_by(region) %>%
  dplyr::summarise(value = mean(value))

df_star_zip$region <- as.character(df_star_zip$region)

#map the star ratings for NYC
ny_map = ZipChoropleth$new(df_star_zip)
nyc_fips = c(36005, 36047, 36061, 36081, 36085)
ny_map$set_zoom_zip(state_zoom = "new york", county_zoom = nyc_fips, msa_zoom = NULL, zip_zoom = NULL)
ny_map$title = "HCAHPS Star Rating by Zip Code for NYC"

ny_map$ggplot_scale = scale_fill_brewer(name="Average Star Rating", palette= "RdYlGn", drop=FALSE)


ggsave(filename="NYMap.png",plot=ny_map$render(), path = "~/cs107/Hospital-Ranking-CS107")

```


